name: webinar_x
description: "A new Flutter project."
publish_to: '_none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^3.0.1
  jitsi_meet: ^4.0.0
  intl: ^0.17.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/ic_meeting.png
    - lib/assets/images/ic_google.png
    - lib/assets/images/ic_chat.png
    - lib/assets/images/ic_WebinarX.png


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/ic_WebinarX.png"



